name: approval-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs the workflow at 00:00 on the first day of every month
    - cron: '0 0 1 * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Approval Tests for Macro Expansion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly # macro expansion tests need the nightly toolchain
          override: true
      - run: cargo install cargo-expand #this is potentially slower than using the action below
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: macro_expansion # explicitly only run the tests from the macro_expansion module
